version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: istanbuilders_db
    environment:
      POSTGRES_DB: complaints_db
      POSTGRES_USER: istanbuilders
      POSTGRES_PASSWORD: istanbuilders123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
